/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'surface-container-highest': '#dae2fd',
        'error-container': '#ffdad6',
        'on-tertiary-fixed': '#001e2f',
        'outline': '#727783',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'secondary': '#bb0013',
        'tertiary': '#004869',
        'inverse-on-surface': '#eef0ff',
        'primary-fixed-dim': '#a7c8ff',
        'surface-container-high': '#e2e7ff',
        'on-primary-fixed': '#001b3b',
        'on-tertiary-fixed-variant': '#004c6e',
        'primary-container': '#005bac',
        'tertiary-fixed-dim': '#89ceff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#004788',
        'secondary-fixed': '#ffdad6',
        'on-secondary-container': '#fffbff',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'surface-variant': '#dae2fd',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#ffb4ab',
        'tertiary-fixed': '#c9e6ff',
        'surface-container-low': '#f2f3ff',
        'on-error-container': '#93000a',
        'surface-tint': '#0b5eaf',
        'on-surface-variant': '#424751',
        'tertiary-container': '#00618c',
        'outline-variant': '#c2c6d3',
        'on-secondary-fixed': '#410002',
        'primary-fixed': '#d5e3ff',
        'on-background': '#131b2e',
        'inverse-primary': '#a7c8ff',
        'on-primary-container': '#bdd5ff',
        'background': '#faf8ff',
        'surface-container': '#eaedff',
        'on-tertiary-container': '#a8d9ff',
        'inverse-surface': '#283044',
        'secondary-container': '#e71520',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#93000d',
        'on-surface': '#131b2e',
        'primary': '#004482',
        'surface': '#faf8ff',
        mobifone: {
          blue: '#005BAC',
          red: '#ED1C24',
          sky: '#0EA5E9',
          canvas: '#FAF8FF',
          surface: '#FFFFFF',
          dark: '#131B2E',
          muted: '#64748B',
          lightBlue: '#E2E7FF',
          softBlue: '#F2F3FF',
        },
      },
      spacing: {
        'space-3xl': '40px',
        'margin': '16px',
        'space-md': '16px',
        'space-sm': '12px',
        'gutter': '12px',
        'space-4xl': '48px',
        'space-xs': '8px',
        'space-xl': '24px',
        'space-lg': '20px',
        'space-2xs': '4px',
        'space-2xl': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        button: ['Inter', 'sans-serif'],
        h1: ['Inter', 'sans-serif'],
        'button-sm': ['Inter', 'sans-serif'],
        h2: ['Inter', 'sans-serif'],
        h3: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'button': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'h1': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'button-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'h2': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'display': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
