import { Store, StoreServiceInfo } from '../models/store.types';

export const STORE_SERVICES_CATALOG: StoreServiceInfo[] = [
    {
        code: 'SIM_REGISTRATION',
        name: 'Dang ky thong tin chinh chu / Doi SIM',
        description: 'Chuan hoa thong tin thue bao theo Nghi dinh 49, cap lai SIM mat/hong',
    },
    {
        code: 'ESIM_SWAP',
        name: 'Doi eSIM',
        description: 'Ho tro chuyen doi SIM vat ly sang eSIM tren iPhone, Android, Smartwatch',
    },
    {
        code: 'PACKAGE_CONSULTATION',
        name: 'Tu van & Dang ky goi cuoc 4G/5G',
        description: 'Dang ky cac goi cuoc uu dai Data toc do cao, combo thoai va data',
    },
    {
        code: 'BILL_PAYMENT',
        name: 'Thanh toan cuoc & Nap tien',
        description: 'Thu cuoc thue bao tra sau, nap the cao, nap tien tai khoan dien tu',
    },
    {
        code: 'B2B_SUPPORT',
        name: 'Khach hang Doanh nghiep (KHDN)',
        description: 'Hoa don dien tu, chu ky so, tin nhan thuong hieu SMS Brandname',
    },
    {
        code: 'WARRANTY',
        name: 'Ho tro ky thuat thiet bi & khieu nai',
        description: 'Tiep nhan phan anh chat luong mang, huong dan cai dat APN va roaming',
    },
];

export const MOBIFONE_CAMAU_STORES: Store[] = [
    {
        id: 'STORE_CM_MAIN',
        code: 'CM001',
        name: 'Cua hang MobiFone Thanh pho Ca Mau (Tru so Tinh)',
        districtId: 'TP_CA_MAU',
        districtName: 'Thanh pho Ca Mau',
        wardName: 'Phuong 5',
        address: 'So 1-3 Luu Tan Tai, Phuong 5, TP. Ca Mau, Tinh Ca Mau',
        latitude: 9.1768,
        longitude: 105.1504,
        hotline: '0290 3838 888',
        openingHours: '07:30 - 20:00 (Thu 2 - Chu Nhat, ke ca ngay le)',
        services: [
            'SIM_REGISTRATION',
            'ESIM_SWAP',
            'PACKAGE_CONSULTATION',
            'BILL_PAYMENT',
            'B2B_SUPPORT',
            'WARRANTY',
        ],
        isMainBranch: true,
    },
    {
        id: 'STORE_CAI_NUOC',
        code: 'CM002',
        name: 'Cua hang MobiFone Huyen Cai Nuoc',
        districtId: 'HUYEN_CAI_NUOC',
        districtName: 'Huyen Cai Nuoc',
        wardName: 'Thi tran Cai Nuoc',
        address: 'Khom 2, Thi tran Cai Nuoc, Huyen Cai Nuoc, Tinh Ca Mau',
        latitude: 9.0152,
        longitude: 105.0345,
        hotline: '0290 3883 123',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_DAM_DOI',
        code: 'CM003',
        name: 'Cua hang MobiFone Huyen Dam Doi',
        districtId: 'HUYEN_DAM_DOI',
        districtName: 'Huyen Dam Doi',
        wardName: 'Thi tran Dam Doi',
        address: 'Duong 30/4, Khom 4, Thi tran Dam Doi, Huyen Dam Doi, Tinh Ca Mau',
        latitude: 9.0289,
        longitude: 105.2154,
        hotline: '0290 3858 234',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_NAM_CAN',
        code: 'CM004',
        name: 'Cua hang MobiFone Huyen Nam Can',
        districtId: 'HUYEN_NAM_CAN',
        districtName: 'Huyen Nam Can',
        wardName: 'Thi tran Nam Can',
        address: 'Ap Hang Vinh, Thi tran Nam Can, Huyen Nam Can, Tinh Ca Mau',
        latitude: 8.7562,
        longitude: 104.9821,
        hotline: '0290 3877 345',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_NGOC_HIEN',
        code: 'CM005',
        name: 'Cua hang MobiFone Huyen Ngoc Hien',
        districtId: 'HUYEN_NGOC_HIEN',
        districtName: 'Huyen Ngoc Hien',
        wardName: 'Thi tran Rach Goc',
        address: 'Khom 8, Thi tran Rach Goc, Huyen Ngoc Hien, Tinh Ca Mau',
        latitude: 8.6189,
        longitude: 104.9876,
        hotline: '0290 3871 456',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_PHU_TAN',
        code: 'CM006',
        name: 'Cua hang MobiFone Huyen Phu Tan',
        districtId: 'HUYEN_PHU_TAN',
        districtName: 'Huyen Phu Tan',
        wardName: 'Thi tran Cai Doi Vam',
        address: 'Duong 3/2, Khom 1, Thi tran Cai Doi Vam, Huyen Phu Tan, Tinh Ca Mau',
        latitude: 8.9482,
        longitude: 104.8876,
        hotline: '0290 3889 567',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_THOI_BINH',
        code: 'CM007',
        name: 'Cua hang MobiFone Huyen Thoi Binh',
        districtId: 'HUYEN_THOI_BINH',
        districtName: 'Huyen Thoi Binh',
        wardName: 'Thi tran Thoi Binh',
        address: 'Khom 1, Thi tran Thoi Binh, Huyen Thoi Binh, Tinh Ca Mau',
        latitude: 9.3512,
        longitude: 105.1432,
        hotline: '0290 3861 678',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_TRAN_VAN_THOI',
        code: 'CM008',
        name: 'Cua hang MobiFone Huyen Tran Van Thoi',
        districtId: 'HUYEN_TRAN_VAN_THOI',
        districtName: 'Huyen Tran Van Thoi',
        wardName: 'Thi tran Tran Van Thoi',
        address: 'Khom 1, Thi tran Tran Van Thoi, Huyen Tran Van Thoi, Tinh Ca Mau',
        latitude: 9.1824,
        longitude: 104.9812,
        hotline: '0290 3895 789',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_SONG_DOC',
        code: 'CM009',
        name: 'Diem Giao Dich MobiFone Thi tran Song Doc',
        districtId: 'HUYEN_TRAN_VAN_THOI',
        districtName: 'Huyen Tran Van Thoi',
        wardName: 'Thi tran Song Doc',
        address: 'Khom 7, Thi tran Song Doc, Huyen Tran Van Thoi, Tinh Ca Mau',
        latitude: 9.0832,
        longitude: 104.8415,
        hotline: '0290 3890 890',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_U_MINH',
        code: 'CM010',
        name: 'Cua hang MobiFone Huyen U Minh',
        districtId: 'HUYEN_U_MINH',
        districtName: 'Huyen U Minh',
        wardName: 'Thi tran U Minh',
        address: 'Khom 3, Thi tran U Minh, Huyen U Minh, Tinh Ca Mau',
        latitude: 9.3541,
        longitude: 104.9912,
        hotline: '0290 3865 901',
        openingHours: '07:30 - 17:30 (Thu 2 - Thu 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
];
