import { Store, StoreServiceInfo } from '../models/store.types';

export const STORE_SERVICES_CATALOG: StoreServiceInfo[] = [
    {
        code: 'SIM_REGISTRATION',
        name: 'Đăng ký thông tin chính chủ / Đổi SIM',
        description: 'Chuẩn hóa thông tin thuê bao theo Nghị định 49, cấp lại SIM mất/hỏng',
    },
    {
        code: 'ESIM_SWAP',
        name: 'Đổi eSIM',
        description: 'Hỗ trợ chuyển đổi SIM vật lý sang eSIM trên iPhone, Android, Smartwatch',
    },
    {
        code: 'PACKAGE_CONSULTATION',
        name: 'Tư vấn & Đăng ký gói cước 4G/5G',
        description: 'Đăng ký các gói cước ưu đãi Data tốc độ cao, combo thoại và data',
    },
    {
        code: 'BILL_PAYMENT',
        name: 'Thanh toán cước & Nạp tiền',
        description: 'Thu cước thuê bao trả sau, nạp thẻ cào, nạp tiền tài khoản điện tử',
    },
    {
        code: 'B2B_SUPPORT',
        name: 'Khách hàng Doanh nghiệp (KHDN)',
        description: 'Hóa đơn điện tử, chữ ký số, tin nhắn thương hiệu SMS Brandname',
    },
    {
        code: 'WARRANTY',
        name: 'Hỗ trợ kỹ thuật thiết bị & khiếu nại',
        description: 'Tiếp nhận phản ánh chất lượng mạng, hướng dẫn cài đặt APN và roaming',
    },
];

export const MOBIFONE_CAMAU_STORES: Store[] = [
    {
        id: 'STORE_CM_MAIN',
        code: 'CM001',
        name: 'Cửa hàng MobiFone Thành phố Cà Mau (Trụ sở Tỉnh)',
        districtId: 'TP_CA_MAU',
        districtName: 'Thành phố Cà Mau',
        wardName: 'Phường 5',
        address: 'Số 1-3 Lưu Tấn Tài, Phường 5, TP. Cà Mau, Tỉnh Cà Mau',
        latitude: 9.1768,
        longitude: 105.1504,
        hotline: '0290 3838 888',
        openingHours: '07:30 - 20:00 (Thứ 2 - Chủ Nhật, kể cả ngày lễ)',
        services: [
            'SIM_REGISTRATION',
            'ESIM_SWAP',
            'PACKAGE_CONSULTATION',
            'BILL_PAYMENT',
            'B2B_SUPPORT',
            'WARRANTY',
        ],
        isMainBranch: true,
    },
    {
        id: 'STORE_CAI_NUOC',
        code: 'CM002',
        name: 'Cửa hàng MobiFone Huyện Cái Nước',
        districtId: 'HUYEN_CAI_NUOC',
        districtName: 'Huyện Cái Nước',
        wardName: 'Thị trấn Cái Nước',
        address: 'Khóm 2, Thị trấn Cái Nước, Huyện Cái Nước, Tỉnh Cà Mau',
        latitude: 9.0152,
        longitude: 105.0345,
        hotline: '0290 3883 123',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_DAM_DOI',
        code: 'CM003',
        name: 'Cửa hàng MobiFone Huyện Đầm Dơi',
        districtId: 'HUYEN_DAM_DOI',
        districtName: 'Huyện Đầm Dơi',
        wardName: 'Thị trấn Đầm Dơi',
        address: 'Đường 30/4, Khóm 4, Thị trấn Đầm Dơi, Huyện Đầm Dơi, Tỉnh Cà Mau',
        latitude: 9.0289,
        longitude: 105.2154,
        hotline: '0290 3858 234',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_NAM_CAN',
        code: 'CM004',
        name: 'Cửa hàng MobiFone Huyện Năm Căn',
        districtId: 'HUYEN_NAM_CAN',
        districtName: 'Huyện Năm Căn',
        wardName: 'Thị trấn Năm Căn',
        address: 'Ấp Hàng Vịnh, Thị trấn Năm Căn, Huyện Năm Căn, Tỉnh Cà Mau',
        latitude: 8.7562,
        longitude: 104.9821,
        hotline: '0290 3877 345',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_NGOC_HIEN',
        code: 'CM005',
        name: 'Cửa hàng MobiFone Huyện Ngọc Hiển',
        districtId: 'HUYEN_NGOC_HIEN',
        districtName: 'Huyện Ngọc Hiển',
        wardName: 'Thị trấn Rạch Gốc',
        address: 'Khóm 8, Thị trấn Rạch Gốc, Huyện Ngọc Hiển, Tỉnh Cà Mau',
        latitude: 8.6189,
        longitude: 104.9876,
        hotline: '0290 3871 456',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_PHU_TAN',
        code: 'CM006',
        name: 'Cửa hàng MobiFone Huyện Phú Tân',
        districtId: 'HUYEN_PHU_TAN',
        districtName: 'Huyện Phú Tân',
        wardName: 'Thị trấn Cái Đôi Vàm',
        address: 'Đường 3/2, Khóm 1, Thị trấn Cái Đôi Vàm, Huyện Phú Tân, Tỉnh Cà Mau',
        latitude: 8.9482,
        longitude: 104.8876,
        hotline: '0290 3889 567',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_THOI_BINH',
        code: 'CM007',
        name: 'Cửa hàng MobiFone Huyện Thới Bình',
        districtId: 'HUYEN_THOI_BINH',
        districtName: 'Huyện Thới Bình',
        wardName: 'Thị trấn Thới Bình',
        address: 'Khóm 1, Thị trấn Thới Bình, Huyện Thới Bình, Tỉnh Cà Mau',
        latitude: 9.3512,
        longitude: 105.1432,
        hotline: '0290 3861 678',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_TRAN_VAN_THOI',
        code: 'CM008',
        name: 'Cửa hàng MobiFone Huyện Trần Văn Thời',
        districtId: 'HUYEN_TRAN_VAN_THOI',
        districtName: 'Huyện Trần Văn Thời',
        wardName: 'Thị trấn Trần Văn Thời',
        address: 'Khóm 1, Thị trấn Trần Văn Thời, Huyện Trần Văn Thời, Tỉnh Cà Mau',
        latitude: 9.1824,
        longitude: 104.9812,
        hotline: '0290 3895 789',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_SONG_DOC',
        code: 'CM009',
        name: 'Điểm Giao Dịch MobiFone Thị trấn Sông Đốc',
        districtId: 'HUYEN_TRAN_VAN_THOI',
        districtName: 'Huyện Trần Văn Thời',
        wardName: 'Thị trấn Sông Đốc',
        address: 'Khóm 7, Thị trấn Sông Đốc, Huyện Trần Văn Thời, Tỉnh Cà Mau',
        latitude: 9.0832,
        longitude: 104.8415,
        hotline: '0290 3890 890',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
    {
        id: 'STORE_U_MINH',
        code: 'CM010',
        name: 'Cửa hàng MobiFone Huyện U Minh',
        districtId: 'HUYEN_U_MINH',
        districtName: 'Huyện U Minh',
        wardName: 'Thị trấn U Minh',
        address: 'Khóm 3, Thị trấn U Minh, Huyện U Minh, Tỉnh Cà Mau',
        latitude: 9.3541,
        longitude: 104.9912,
        hotline: '0290 3865 901',
        openingHours: '07:30 - 17:30 (Thứ 2 - Thứ 7)',
        services: ['SIM_REGISTRATION', 'ESIM_SWAP', 'PACKAGE_CONSULTATION', 'BILL_PAYMENT'],
        isMainBranch: false,
    },
];
