import { TelecomPackage } from '../models/package.types';

export const TELECOM_PACKAGES: TelecomPackage[] = [
    {
        id: 'pkg-kc135',
        code: 'KC135',
        name: 'Goi Cuoc KC135 Dinh Cao Data & Thoai',
        price: 135000,
        cycle: '30 ngay',
        dataPerDay: '6GB/Ngay',
        totalData: '180GB/Thang',
        voiceInternal: 'Mien phi cuoc goi noi mang duoi 10 phut (toi da 1.000 phut)',
        voiceExternal: '50 phut thoai ngoai mang',
        sms: 'Gia cuoc thong thuong theo quy dinh',
        description: 'Goi cuoc duoc ua chuong nhat tai Ca Mau danh cho khach hang co nhu cau livestream, xem video chat luong cao va lien lac thuong xuyen.',
        category: 'COMBO_VOICE_DATA',
        status: 'ACTIVE',
        isHot: true,
        isPromotional: true,
        registrationSyntax: 'DK KC135 gui 999 hoac dang ky truc tiep qua Mini App',
        cancellationSyntax: 'HUY KC135 gui 999',
        targetAudience: 'Thue bao tra truoc va tra sau MobiFone phat trien moi hoac nhan duoc tin nhan moi dang ky',
        benefits: [
            '6GB Data toc do cao moi ngay, het dung luong ngat ket noi de tranh phat sinh cuoc',
            'Thoai noi mang tha ga, mien phi cac cuoc goi duoi 10 phut',
            '50 phut goi lien mang trong nuoc',
            'Uu tien bang thong mang 5G khi co phu song tai TP Ca Mau',
        ],
    },
    {
        id: 'pkg-pt120',
        code: 'PT120',
        name: 'Goi Cuoc PT120 Data Toc Do Cao',
        price: 120000,
        cycle: '30 ngay',
        dataPerDay: '2GB/Ngay',
        totalData: '60GB/Thang',
        voiceInternal: 'Khong bao gom',
        voiceExternal: 'Khong bao gom',
        description: 'Goi data tieu chuan danh cho thue bao su dung Internet di dong, luot web, mang xa hoi moi ngay.',
        category: 'DATA_HEAVY',
        status: 'ACTIVE',
        isHot: true,
        isPromotional: false,
        registrationSyntax: 'DK PT120 gui 999',
        cancellationSyntax: 'HUY PT120 gui 999',
        targetAudience: 'Tat ca thue bao di dong tra truoc va tra sau MobiFone tren toan tinh Ca Mau',
        benefits: [
            '2GB Data toc do cao moi ngay (60GB/thang)',
            'Gia cuoc tiet kiem chi 4.000d/ngay',
            'Tu dong gia han sau 30 ngay neu tai khoan chinh du cuoc',
        ],
    },
    {
        id: 'pkg-mxh120',
        code: 'MXH120',
        name: 'Goi Cuoc MXH120 Mien Phi Mang Xa Hoi',
        price: 120000,
        cycle: '30 ngay',
        dataPerDay: '1GB/Ngay',
        totalData: '30GB/Thang + Khong gioi han Data MXH',
        voiceInternal: 'Mien phi goi noi mang duoi 10 phut',
        voiceExternal: '30 phut thoai ngoai mang',
        description: 'Dac quyen xem TikTok, YouTube, Facebook va chat Messenger khong gioi han dung luong suot 30 ngay.',
        category: 'COMBO_VOICE_DATA',
        status: 'ACTIVE',
        isHot: true,
        isPromotional: true,
        registrationSyntax: 'DK MXH120 gui 999',
        cancellationSyntax: 'HUY MXH120 gui 999',
        targetAudience: 'Thue bao tra truoc kich hoat moi hoac thuoc danh sach uu dai',
        benefits: [
            'Mien phi 100% Data toc do cao su dung ung dung TikTok, YouTube, Facebook',
            '1GB Data/ngay de truy cap cac ung dung khac',
            'Mien phi goi noi mang duoi 10 phut va 30 phut ngoai mang',
        ],
    },
    {
        id: 'pkg-tk135',
        code: 'TK135',
        name: 'Goi Cuoc TK135 Sieu Data 7GB/Ngay',
        price: 135000,
        cycle: '30 ngay',
        dataPerDay: '7GB/Ngay',
        totalData: '210GB/Thang',
        voiceInternal: 'Khong bao gom',
        voiceExternal: 'Khong bao gom',
        description: 'Goi cuoc danh cho nguoi dung chuyen Data dung luong cuc khung, choi game va xem video 4K khong lo ngat quang.',
        category: 'DATA_HEAVY',
        status: 'ACTIVE',
        isHot: false,
        isPromotional: false,
        registrationSyntax: 'DK TK135 gui 999',
        cancellationSyntax: 'HUY TK135 gui 999',
        targetAudience: 'Thue bao phat trien moi tai khu vuc tinh Ca Mau',
        benefits: [
            '7GB Data toc do cao moi ngay',
            'Toc do 4G/5G on dinh ca ngay lan dem',
            'Het data ngat ket noi tranh phat sinh chi phi ngoai y muon',
        ],
    },
    {
        id: 'pkg-6kc135',
        code: '6KC135',
        name: 'Goi Cuoc 6KC135 (6 Thang Tang 1 Thang)',
        price: 810000,
        cycle: '210 ngay (7 thang)',
        dataPerDay: '6GB/Ngay',
        totalData: '1.260GB/Chu ky',
        voiceInternal: 'Mien phi cuoc goi noi mang duoi 10 phut',
        voiceExternal: '50 phut thoai ngoai mang moi thang',
        description: 'Chu ky dai tiet kiem chi phi, su dung lien tuc 7 thang voi gia 6 thang, khong lo quen nap tien gia han.',
        category: 'LONG_CYCLE',
        status: 'ACTIVE',
        isHot: false,
        isPromotional: true,
        registrationSyntax: 'DK 6KC135 gui 999',
        cancellationSyntax: 'HUY 6KC135 gui 999',
        targetAudience: 'Thue bao dang su dung hoac kich hoat moi tai Ca Mau',
        benefits: [
            'Khuyen mai tang them 1 thang su dung mien phi (Tong 7 thang)',
            '6GB Data moi ngay xuyen suot chu ky',
            'Lien lac khong gian doan voi goi cuoc dai han',
        ],
    },
    {
        id: 'pkg-12kc135',
        code: '12KC135',
        name: 'Goi Cuoc 12KC135 (12 Thang Tang 2 Thang)',
        price: 1620000,
        cycle: '420 ngay (14 thang)',
        dataPerDay: '6GB/Ngay',
        totalData: '2.520GB/Chu ky',
        voiceInternal: 'Mien phi cuoc goi noi mang duoi 10 phut',
        voiceExternal: '50 phut thoai ngoai mang moi thang',
        description: 'Goi cuoc nam uu dai lon nhat: Su dung 14 thang, chi tra phi 12 thang. Tron ven 1 nam an tam ket noi.',
        category: 'LONG_CYCLE',
        status: 'ACTIVE',
        isHot: true,
        isPromotional: true,
        registrationSyntax: 'DK 12KC135 gui 999',
        cancellationSyntax: 'HUY 12KC135 gui 999',
        targetAudience: 'Thue bao tra truoc va tra sau MobiFone',
        benefits: [
            'Tang ngay 2 thang su dung mien phi (Tong 14 thang)',
            '6GB Data moi ngay xuyen suot 14 thang',
            'Khong can thao tac nap the gia han hang thang',
        ],
    },
];

export function getActivePackages(): TelecomPackage[] {
    return TELECOM_PACKAGES.filter((p) => p.status === 'ACTIVE');
}

export function getPackageByCode(code: string): TelecomPackage | undefined {
    return TELECOM_PACKAGES.find((p) => p.code.toUpperCase() === code.toUpperCase());
}

export function getHotPackages(): TelecomPackage[] {
    return TELECOM_PACKAGES.filter((p) => p.status === 'ACTIVE' && p.isHot);
}
